!!python/dict
  osimage:
    imagetype:
    - "T{osimage.imagetype}"
    - "W:T{winimage.imagename}=${{imgtype=V{imagetype}: V{obj_name} if imgtype == 'windows' else None }}"
    - "W:T{linuximage.imagename}=${{imgtype=V{imagetype}: V{obj_name} if imgtype == 'linux' else None }}"
    - "C:${{value=V{imagetype}: True if str(value) in ('windows','linux') else False}}"
    basic_attributes:
      distribution: "T{osimage.osvers}"
      arch: "T{osimage.osarch}"
      osdistro: "T{osimage.osdistroname}"
      osname: "T{osimage.osname}"
      description: "T{osimage.description}"
      groups: "T{osimage.groups}"
    role: 
    - "T{osimage.profile}"
    - "C:${{value=V{role}: True if str(value) in ('compute','service') else False}}"
    provision_mode: 
    - "T{osimage.provmethod}"
    - "C:${{value=V{provision_mode}: True if str(value) in ('install','netboot','statelite') else False}}"
    package_selection:
      pkglist: "T{linuximage.pkglist}"
      pkgdir: "T{linuximage.pkgdir}"
      otherpkglist: "T{linuximage.otherpkglist}"
      otherpkgdir: "T{linuximage.otherpkgdir}"
    osupdatename: "T{osimage.osupdatename}"
    kernel_driver:
      driverupdatesrc: "T{linuximage.driverupdatesrc}"
      netdrivers: "T{linuximage.netdrivers}"
      kerneldir: "T{linuximage.kerneldir}"
      kernelver: "T{linuximage.kernelver}"
    scripts:
      postscripts: "T{osimage.postscripts}"
      postbootscripts: "T{osimage.postbootscripts}"
    kernel_dump:
      dump: "T{linuximage.dump}"
      crashkernelsize: "T{linuximage.crashkernelsize}"
    template: "${{imagetype=V{imagetype} :T{winimage.template} if imagetype == 'windows' else T{linuximage.template} if imagetype == 'linux' else None }} "
    diskpartitionspec: "${{imagetype=V{imagetype} :T{linuximage.partitionfile} if imagetype == 'linux' else T{winimage.partitionfile} if imagetype == 'windows' else None}}"
    filestosync: "T{osimage.synclists}"
    addkcmdline: "T{linuximage.addkcmdline}"
    boottarget: "T{linuximage.boottarget}"                                 
    genimgoptions:
      exlist: "T{linuximage.exlist}"
      postinstall: "T{linuximage.postinstall}"
      rootimgdir: "T{linuximage.rootimgdir}"
      nodebootif: "T{linuximage.nodebootif}"
      permission: "T{linuximage.permission}"
      rootfstype: 
      - "T{osimage.rootfstype}"
      - "C:${{value=V{genimgoptions.rootfstype}: True if str(value) in ('','nfs','ramdisk') else False}}"
      installto: "${{imagetype=V{imagetype} :T{winimage.installto} if imagetype == 'windows' else None }}"
      winpepath: "${{imagetype=V{imagetype} :T{winimage.winpepath}  if imagetype == 'windows' else None }}"
    deprecated:
      nimimageshared_home: "T{nimimage.shared_home}"
      nimimageconfigdump: "T{nimimage.configdump}"
      nimimagespot: "T{nimimage.spot}"
      nimimagenimtype: "T{nimimage.nimtype}"
      nimimagemksysb: "T{nimimage.mksysb}"
      nimimagehome: "T{nimimage.home}"
      nimimagenimmethod: "T{nimimage.nimmethod}"
      nimimagefb_script: "T{nimimage.fb_script}"
      nimimagedump: "T{nimimage.dump}"
      cfmdir: "T{osimage.cfmdir}"
      nimimagecomments: "T{nimimage.comments}"
      serverrole: "T{osimage.serverrole}"
      nimimageroot: "T{nimimage.root}"
      nimimageinstallp_bundle: "T{nimimage.installp_bundle}"
      nimimageotherpkgs: "T{nimimage.otherpkgs}"
      nimimageresolv_conf: "T{nimimage.resolv_conf}"
      nimimagepaging: "T{nimimage.paging}"
      nimimagescript: "T{nimimage.script}"
      nimimageshared_root: "T{nimimage.shared_root}"
      nimimagebosinst_data: "T{nimimage.bosinst_data}"
      nimimagelpp_source: "T{nimimage.lpp_source}"
      kitcomponents: "T{osimage.kitcomponents}"
      nimimageimage_data: "T{nimimage.image_data}"
      isdeletable: "T{osimage.isdeletable}"
      nimimagetmp: "T{nimimage.tmp}"
      otherifce: "T{linuximage.otherifce}"
      comments: "T{linuximage.comments}"
      krpmver: "T{linuximage.krpmver}"
