!!python/dict
  node:
    schema_version: "1.0"
    obj_type: 
    - "${{ groupname=T{nodegroup.groupname}, nodename=T{nodelist.node},objname=V{obj_name} :'node' if nodename == objname else 'group'}}"
    - "W:T{nodegroup.groupname}=${{objtype=V{obj_type}: V{obj_name} if objtype=='group' else None}}"
    - "W:T{nodelist.node}=${{objtype=V{obj_type}: V{obj_name} if objtype=='node' else None}}"
    obj_info: 
      groups: "${{ objtype=V{obj_type} : T{nodelist.groups} if objtype == 'node' else None}}"
      grouptype: "${{objtype=V{obj_type} :  T{nodegroup.grouptype} if objtype == 'group' else None}}"
      members: "${{objtype=V{obj_type} : T{nodegroup.members} if objtype == 'group' else None}}"
      filter: "${{ objtype=V{obj_type} : T{nodegroup.wherevals} if objtype == 'group' else None}}"
      description: "T{nodelist.comments}"
    device_type: 
    - "${{ switchname=T{switches.switch}, pduname=T{pdu.node}, objname=V{obj_name}, rackname=T{rack.rackname},hcpname=T{ppchcp.hcp}: 'switch' if switchname == objname else 'pdu' if pduname == objname else 'rack' if rackname == objname else 'hmc' if hcpname == objname else 'server' }}"
    - "W:T{switches.switch}=${{devtype=V{device_type}: V{obj_name} if devtype == 'switch' else None}}"
    - "W:T{pdu.node}=${{devtype=V{device_type}: V{obj_name} if devtype == 'pdu' else None}}" 
    - "W:T{rack.rackname}=${{devtype=V{device_type}: V{obj_name} if devtype == 'rack' else None}}" 
    device_info:
      arch: "T{nodetype.arch}"
      supportedarchs: "T{nodetype.supportedarchs}"
      disksize: "T{hwinv.disksize}"
      memory: "T{hwinv.memory}"
      cputype: "T{hwinv.cputype}"
      cpucount: "T{hwinv.cpucount}"
      mtm: "T{vpd.mtm}"
      uuid: "T{vpd.uuid}"
      switchtype: "${{devtype=V{device_type}: T{switches.switchtype} if devtype == 'switch' else None}}"
      pdutype:  "${{devtype=V{device_type}: T{pdu.pdutype} if devtype == 'pdu' else None}}"
      outlets: "${{devtype=V{device_type}: T{pdu.outlet} if devtype == 'pdu' else None}}"
      model: "${{devtype=V{device_type}: T{pdu.modelnum} if devtype == 'pdu' else None}}"
      serial: "${{ devtype=V{device_type}: T{pdu.serialnum} if devtype == 'pdu' else T{vpd.serial} }}"
      characteristics: "T{nodetype.nodetype}"
      displayname: "${{ devtype=V{device_type}: T{rack.displayname} if devtype == 'rack' else None }}"
      rackno: "${{ devtype=V{device_type}: T{rack.num} if devtype == 'rack' else None }}"
      height: "${{ devtype=V{device_type}: T{rack.height} if devtype == 'rack' else None }}"
      room: "${{ devtype=V{device_type}: T{rack.room} if devtype == 'rack' else None }}"
    position_info:
      rack: "T{nodepos.rack}"
      unit: "T{nodepos.u}"
      chassis: "T{nodepos.chassis}"
      slot: "T{nodepos.slot}"
      room: "T{nodepos.room}"
      height: "T{nodepos.height}"
    domain_info:
      ou: "T{domain.ou}"
      authdomain: "T{domain.authdomain}"
      adminuser: "T{domain.adminuser}"
      adminpassword: "T{domain.adminpassword}"
      type: "T{domain.type}"
    security_info:
      snmp:
        securitylevel: "T{pdu.seclevel}"
        version: "${{devtype=V{device_type}: T{switches.snmpversion} if devtype == 'switch' else T{pdu.snmpversion} if devtype in ('pdu') else None}}"
        authprotocol: "${{ devtype=V{device_type}: T{switches.auth} if devtype in ('switch') else T{pdu.authtype} if devtype in ('pdu')  else None  }}" 
        privacyprotocol: "${{devtype=V{device_type}: T{switches.privacy} if devtype == 'switch' else T{pdu.privtype} if devtype in ('pdu')  else  None }}"
        community: "${{devtype=V{device_type},snmpver=V{security_info.snmp.version}: T{pdu.community} if devtype in ('pdu') and snmpver in ('SNMPv1','SNMPv2') else T{switches.password} if devtype == 'switch' and snmpver in ('SNMPv1','SNMPv2') else None}}"
        username: "${{devtype=V{device_type}: T{switches.username} if devtype == 'switch' else T{pdu.snmpuser} if devtype in ('pdu') else None}}"
        authkey: "${{devtype=V{device_type}: T{switches.password} if devtype == 'switch' else T{pdu.authkey} if devtype in ('pdu') else None}}"
        privkey: "T{pdu.privkey}"
      remotecontrol:
        username: "${{devtype=V{device_info.characteristics}: T{switches.sshusername} if devtype == 'switch' else T{pdu.username} if devtype in ('pdu') else T{ppchcp.username} if devtype in ('hmc','ivm','ppc') else T{mpa.username} if devtype in ('mm')  else None}}" 
        password: "${{devtype=V{device_info.characteristics}: T{switches.sshpassword} if devtype == 'switch' else T{pdu.password}  if devtype in ('pdu') else T{ppchcp.password} if devtype in ('hmc','ivm','ppc') else T{mpa.password} if devtype in ('mm')  else None}}"
        remoteprotocol: "T{switches.protocol}"
      zonename: "T{nodelist.zonename}"
      productkey: "T{prodkey.key}"
    network_info:
      linkports: "${{devtype=V{device_type}: T{switches.linkports} if devtype == 'switch' else None}}"
      otherinterfaces: "T{hosts.otherinterfaces}"
      routenames: "T{noderes.routenames}"
      primarynic: 
        ip: "T{hosts.ip}"
        mac: "T{mac.mac}"    
        hostnames: "T{hosts.hostnames}"
        switch: "T{switch.switch}"
        switchport: "T{switch.port}"
        switchvlan: "T{switch.vlan}"
        switchinterface: "T{switch.interface}"
      nics:
        ips: "T{nics.nicips}"
        hostnamesuffixes: "T{nics.nichostnamesuffixes}"
        hostnameprefixe: "T{nics.nichostnameprefixes}"
        alias: "T{nics.nicaliases}"
        type: "T{nics.nictypes}"
        configscripts: "T{nics.niccustomscripts}"
        networks: "T{nics.nicnetworks}"
        extraconfig: "T{nics.nicextraparams}"
        nicdevices: "T{nics.nicdevices}"
        nicsinfo: "T{nics.nicsadapter}"
    engines:
       hardware_mgt_engine:
          engine_type: "T{nodehm.mgt}"
          engine_info:
            bmc: "${{hwmgtengtype=V{engines.hardware_mgt_engine.engine_type}: T{openbmc.bmc} if hwmgtengtype == 'openbmc' else T{ipmi.bmc} if hwmgtengtype == 'ipmi' else None}}"
            bmcusername: "${{hwmgtengtype=V{engines.hardware_mgt_engine.engine_type}: T{openbmc.username} if hwmgtengtype == 'openbmc' else T{ipmi.username} if hwmgtengtype == 'ipmi' else None}}"
            bmcpassword: "${{hwmgtengtype=V{engines.hardware_mgt_engine.engine_type}: T{openbmc.password} if hwmgtengtype == 'openbmc' else T{ipmi.password} if hwmgtengtype == 'ipmi' else None}}"
            bmcvlantag: "${{hwmgtengtype=V{engines.hardware_mgt_engine.engine_type}: T{openbmc.taggedvlan} if hwmgtengtype == 'openbmc' else T{ipmi.taggedvlan} if hwmgtengtype == 'ipmi' else None}}"
            consport: "T{openbmc.consport}"
            bmcid: "T{ipmi.bmcid}"
            bmcport: "T{ipmi.bmcport}"
            terminalport: "T{nodehm.termport}"                                         
            terminalserver: "T{nodehm.termserver}"
            vmhost: "T{vm.host}"
            vmstorage: "T{vm.storage}"
            vmothersetting: "T{vm.othersettings}"
            vmstoragemodel: "T{vm.storagemodel}"
            vmmemory: "T{vm.memory}"
            vmcpus: "T{vm.cpus}"
            vmnics: "T{vm.nics}"
            vmnicnicmodel: "T{vm.nicmodel}"
            vmvirtflags: "T{vm.virtflags}"
            vmvncport: "T{vm.vncport}"
            vmbootorder: "T{vm.bootorder}"
            vmbeacon: "T{vm.beacon}"
            vmcfgstore: "T{vm.cfgstore}"
            vmcluster: "T{vm.cluster}"
            vmmaster: "T{vm.master}"
            vmmanager: "T{vm.mgr}"
            vmphyslots: "T{vm.physlots}"
            vmstoragecache: "T{vm.storagecache}"
            vmstorageformat: "T{vm.storageformat}"
            vmtextconsole: "T{vm.storageformat}"
            hcp: "${{ hwmgtengtype=V{engines.hardware_mgt_engine.engine_type}: T{zvm.hcp} if hwmgtengtype in ('zvm') else T{ppc.hcp} }}"
            id: "${{hwmgtengtype=V{engines.hardware_mgt_engine.engine_type}: T{mp.id} if hwmgtengtype in ('blade','fsp','ipmi') else T{zvm.userid} if hwmgtengtype in ('zvm') else T{ppc.id}}}"
            mpa: "T{mp.mpa}"
            pprofile: "T{ppc.pprofile}"
            parent: "T{ppc.parent}"
            hwtype: "${{hwmgtengtype=V{engines.hardware_mgt_engine.engine_type},devtype=V{device_type}: T{pdu.nodetype} if devtype == 'pdu' else T{ppc.nodetype} if hwmgtengtype in ('bpa','fsp','ivm','hmc') else T{mp.nodetype} if hwmgtengtype in ('blade','ipmi','openbmc') else T{zvm.nodetype} if hwmgtengtype in ('zvm') else None}}"
            supernode: "T{ppc.supernode}"
            sfp: "T{ppc.sfp}"
       power_mgt_engine:
          engine_type: "T{nodehm.mgt}" 
          engine_info: 
            pdu: "T{pduoutlet.pdu}"
       netboot_engine:
          engine_type: "T{noderes.netboot}" 
          engine_info: 
            installnic: "T{noderes.installnic}"
            discoverynics: "T{noderes.discoverynics}"
            osimage: "T{nodetype.provmethod}"
            chain: "T{chain.chain}"
            addkcmdline: "T{bootparams.addkcmdline}"
            postscripts: "T{postscripts.postscripts}"
            postbootscripts: "T{postscripts.postbootscripts}"
            prescriptsbegin: "T{prescripts.begin}"
            prescriptsend: "T{prescripts.end}"
       console_engine:
          engine_type: "T{nodehm.mgt}"
          engine_info:
            cons: "T{nodehm.cons}"
            conserver: "T{nodehm.conserver}"
            serialport: "T{nodehm.serialport}"
            serialspeed: "T{nodehm.serialspeed}"
            serialflow: "T{nodehm.serialflow}"
            consoleondemand: "T{nodehm.consoleondemand}"
    role: 
    - "${{ snname=T{servicenode.node},objname=V{obj_name}: 'service' if snname ==objname else 'compute'}}"
    - "W:T{servicenode.node}=${{role=V{role}: V{obj_name} if role == 'service' else None}}"
    role_info:
      xcatmaster: "T{noderes.xcatmaster}"
      servicenode: "T{noderes.servicenode}"
      tftpserver: "T{noderes.tftpserver}"
      nfsserver: "T{noderes.nfsserver}"
      monserver: "T{noderes.monserver}"
      nameservers: "T{noderes.nameservers}"
      nodelistprimarysn: "T{nodelist.primarysn}"
      enablesyslog: "T{noderes.syslog}"
      setupnameserver: "${{role=V{role}: T{servicenode.nameserver} if role == 'service' else None}}"
      setupdhcp:  "${{ role=V{role}: T{servicenode.dhcpserver} if role == 'service' else None}}"
      setuptftp: "${{ role=V{role}: T{servicenode.tftpserver} if role == 'service' else None}}"
      setupnfs: "${{ role=V{role}: T{servicenode.nfsserver} if role == 'service' else None}}"
      setupconserver: "${{ role=V{role}: T{servicenode.conserver} if role == 'service' else None}}"
      setupipforward: "${{ role=V{role}: T{servicenode.ipforward} if role == 'service' else None}}"
      setupproxydhcp: "${{ role=V{role}: T{servicenode.proxydhcp} if role == 'service' else None}}"
      setupldap: "${{ role=V{role}: T{servicenode.ldapserver} if role == 'service' else None}}"
      setupntp: "${{ role=V{role}: T{servicenode.ntpserver} if role == 'service' else None}}"
      dhcpinterfaces: "${{ role=V{role}:T{servicenode.dhcpinterfaces} if role == 'service' else None}}"
    deprecated:
      cfgmgtcfgmgr: "T{cfgmgt.cfgmgr}"
      cfgmgtcfgserver: "T{cfgmgt.cfgserver}"
      cfgmgtroles: "T{cfgmgt.roles}"
      chainondiscover: "T{chain.ondiscover}"
      hypervisorcluster: "T{hypervisor.cluster}"
      hypervisorinterface: "T{hypervisor.interface}"
      hypervisormgr: "T{hypervisor.mgr}"
      hypervisortype: "T{hypervisor.type}"
      iscsipasswd: "T{iscsi.passwd}"
      iscsiserver: "T{iscsi.server}"
      iscsitarget: "T{iscsi.target}"
      iscsiuserid: "T{iscsi.userid}"
      macinterface: "T{mac.interface}"
      micbridge: "T{mic.bridge}"
      michost: "T{mic.host}"
      micid: "T{mic.id}"
      micnodetype: "T{mic.nodetype}"
      miconboot: "T{mic.onboot}"
      micpowermgt: "T{mic.powermgt}"
      micvlog: "T{mic.vlog}"
      mpadisplayname: "T{mpa.displayname}"
      mpaslots: "T{mpa.slots}"
      mpaurlpath: "T{mpa.urlpath}"
      nodehmcmdmapping: "T{nodehm.cmdmapping}"
      nodehmgetmac: "T{nodehm.getmac}"
      nodehmpower: "T{nodehm.power}"
      nodelisthidden: "T{nodelist.hidden}"
      noderesnfsdir: "T{noderes.nfsdir}"
      noderesnimserver: "T{noderes.nimserver}"
      noderesprimarynic: "T{noderes.primarynic}"
      noderesproxydhcp: "T{noderes.proxydhcp}"
      pdunodetype: "T{pdu.nodetype}"
      ppcdirectpassword: "T{ppcdirect.password}"
      servicenodeftpserver: "T{servicenode.ftpserver}"
      servicenodenimserver: "T{servicenode.nimserver}"
      storagecontroller: "T{storage.controller}"
      storageosvolume: "T{storage.osvolume}"
      storagetype: "T{storage.type}"
      vmmigrationdest: "T{vm.migrationdest}"
      vmtextconsole: "T{vm.textconsole}"
      vpdside: "T{vpd.side}"
      websrvpassword: "T{websrv.password}"
      websrvport: "T{websrv.port}"
      websrvusername: "T{websrv.username}"
      tftpdir: "T{noderes.tftpdir}"

