!!python/dict
  osimage:
    schema_version: "1.0"
    imagetype:
    - "T{osimage.imagetype}"
    - "W:T{winimage.imagename}=${{imgtype=V{imagetype}: V{obj_name} if imgtype == 'windows' else None }}"
    - "W:T{osimage.imagename}=${{imgtype=V{imagetype}: V{obj_name} if imgtype == 'linux' else None }}"
    basic_attributes:
      distribution: "T{osimage.osvers}"
      arch: "T{osimage.osarch}"
      osdistro: "T{osimage.osdistroname}"
      description: "T{osimage.description}"
    role: "T{osimage.profile}"
    package_selection:
      pkglist: "T{linuximage.pkglist}"
      pkgdir: "T{linuximage.pkgdir}"
      otherpkglist: "T{linuximage.otherpkglist}"
      otherpkgdir: "T{linuximage.otherpkgdir}"
      driverupdatesrc: "T{linuximage.driverupdatesrc}"
      osupdatename: "T{osimage.osupdatename}"
      netdrivers: "T{linuximage.netdrivers}"
      kerneldir: "T{linuximage.kerneldir}"
      kernelver: "T{linuximage.kernelver}"
    provision_mode: "T{osimage.provmethod}"
    template: "${{imagetype=V{imagetype} :T{winimage.template} if imagetype == 'windows' else T{linuximage.template} if imagetype == 'linux' else None }} "
    synclists: "T{osimage.synclists}"
    postscripts: "T{osimage.postscripts}"
    postbootscripts: "T{osimage.postbootscripts}"
    boottarget: "T{linuximage.boottarget}"                                 
    addkcmdline: "T{linuximage.addkcmdline}"
    partitionfile: "${{imagetype=V{imagetype} :T{linuximage.partitionfile} if imagetype == 'linux' else T{winimage.partitionfile} if imagetype == 'windows' else None}}"
    exlist: "T{linuximage.exlist}"
    postinstall: "T{linuximage.postinstall}"
    rootimgdir: "T{linuximage.rootimgdir}"
    nodebootif: "T{linuximage.nodebootif}"
    permission: "T{linuximage.permission}"
    rootfstype: "T{osimage.rootfstype}"
    installto: "${{imagetype=V{imagetype} :T{winimage.installto} if imagetype == 'windows' else None }}"
    winpepath: "${{imagetype=V{imagetype} :T{winimage.winpepath}  if imagetype == 'windows' else None }}"
    kernel_dump:
      dump: "${{imagetype=V{imagetype},provmode=V{provision_mode}: T{linuximage.dump} if imagetype == 'linux' and provmode !='install' else None}}"
      crashkernelsize: "${{imagetype=V{imagetype},provmode=V{provision_mode}: T{linuximage.crashkernelsize} if imagetype == 'linux' and provmode !='install' else None}}"

