!!python/dict  
  policy:
    schema_version: "1.0"
    name: "T{policy.name}"
    host: "T{policy.host}"
    commands: "T{policy.commands}"
    noderange: "T{policy.noderange}"
    parameters: "T{policy.parameters}"
    time: "T{policy.time}"
    rule: "T{policy.rule}"
    usercomment: "T{policy.comments}"
