!!python/dict  
  route:
    schema_version: "1.0"
    net: "T{routes.net}"
    mask: "T{routes.mask}"
    ifname: "T{routes.ifname}"
    gateway: "T{routes.gateway}"
    usercomment: "T{routes.comments}"
