!!python/dict
  node: 
    device_info: 
      arch: nodetype.arch 
    network_info: 
      primarynic: 
        ip: hosts.ip 
        mac: mac.mac     
        switch: switch.switch 
        switchport: switch.port 
    engines: 
        netboot_engine: 
          engine_type: noderes.netboot
          engine_info: 
            installnic: noderes.installnic 
            osimage: nodetype.provmethod 
            addkcmdline: bootparams.addkcmdline 
            postscripts: postscripts.postscripts 
    role_info: 
      xcatmaster: noderes.xcatmaster
